runtime: python311

env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

env_variables:
  PYTHON_ENV: "production"
  ENABLE_METRICS: "true"
  LOG_LEVEL: "INFO"

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: auto
  secure: always

entrypoint: python -m uvicorn src.backend.main:app --host 0.0.0.0 --port $PORT